#%RAML 1.0
title: emp-api
description: API for managing Employee CRUD operations
baseUri: http://localhost:8081/emp
/create-emp:
  description: Used for creating new Employee
  post:
    body:
      application/json:
        example:
          {
            empID: 1,
            empName: "Rishabh",
            empAddress: "India",
            empJob: "Integration Engineer"
          }
    responses:
      200:
        body:
          application/json:
            example:
              {
                status: 200,
                message: "Employee Created"
              }
      500:
        body:
          application/json:
            example:
              {
                status: 500,
                message: "Internal Server Error"
              }
/fetch-employee:
  description: To fetch employees using Employee ID
  get:
    queryParameters:
      empID:
        type: string
        example: "1"
    responses:
      200:
        body:
          application/json:
            example:
              {
                empID: 1,
                empName: "Rishabh",
                empAddress: "India",
                empJob: "Integration Engineer"
              } 
      404:
        body:
          application/json:
            example:
              {
                status: 404,
                message: "Resource Not Found"
              }
      500:
        body:
          application/json:
            example:
              {
                status: 500,
                message: "Internal Server Error"
              }         
/update-employee:
  description: It will update the employee 
  put:
    body:
      application/xml:
        example:
          <?xml version="1.0" encoding="UTF-8"?>
                <emp>
                  <empID>1</empID>
                  <empName>Rishabh</empName>
                  <empAddress>India</empAddress>
                </emp> 
    responses:
      200:
        body:
          application/xml:
            example:
              <?xml version="1.0" encoding="UTF-8"?>
              <response>
                <status>200</status>
                <message>Employee Updated</message>
              </response>
      404:
        body:
          application/json:
            example:
              <?xml version="1.0" encoding="UTF-8"?>
              <response>
                <status>400</status>
                <message>Resource Not Found</message>
              </response>
      500:
        body:
          application/xml:
            example:
              <?xml version="1.0" encoding="UTF-8"?>
              <response>
                <status>500</status>
                <message>Internal Server Error</message>
              </response>
/delete-employee/{empID}:
  description: To Delete employees
  delete:
    responses:
      200:
        body:
          application/json:
            example:
              {
                status: 200,
                message: "Employee Deleted"
              }
      404:
        body:
          application/json:
            example:
              {
                status: 404,
                message: "Employee Not Found"
              }
      500:
        body:
          application/json:
            example:
              {
                status: 500,
                message: "Internal Server Error"
              }
    
      
